.github/workflows/deploy.yml, .github/workflows/test.yml
=> ci: deploy configuration

src/app/layout.tsx
=> fix: test deploy

.github/workflows/deploy.yml
=> ci: trigger deploy action after push

.github/workflows/deploy.yml
=> ci: update known_hosts

.github/workflows/deploy.yml
=> ci: update pem

.github/workflows/deploy.yml
=> ci: update key

.gitignore, app.log
=> fix: delete app.log file

cypress/e2e/navigation.cy.ts, src/components/footer/bottom.tsx, src/components/navbar/nav-menu-item.tsx, src/components/shared/parallax.tsx, src/lib/hooks/use-parallax.ts, src/lib/hooks/use-scroll.ts
=> chore: optimize experience

.github/workflows/deploy_dev.yml, .github/workflows/deploy_prod.yml, aws-upload.js, env.js
=> fix: production env config

components/download/across.tsx, components/download/os-btn.tsx, components/home/hero-section/download-btn.tsx, components/home/index.tsx, components/home/product-showcase/product-showcase.tsx, components/home/product-showcase/title.tsx, components/shared/dropdown-btn.tsx, components/shared/hero-desc.tsx, components/shared/linux-btn-group.tsx, components/shared/over-title.tsx, cypress/e2e/navigation.cy.ts, lib/config/home.tsx, lib/config/pages.tsx, lib/githubAPI.ts, lib/hooks/use-download.ts, styles/app.scss, styles/btn.scss, styles/dark.scss, styles/download.scss, styles/home.scss
=> fix: fix linux download button and optimize experience

.github/workflows/deploy_prod.yml
=> fix: replace ip of production

next.config.js
=> fix: redirect the path of blog to newsletter

app/join/page.tsx, lib/config/pages.tsx
=> fix: close job

components/what-is-new/versions.tsx, lib/config/pages.tsx, lib/versions.ts
=> fix: version order

lib/parseChangelog.ts
=> fix: changelog parse

lib/config/home.tsx, lib/config/pages.tsx, next.config.js
=> fix: apply a X-FRAME header

components/layout/footer.tsx, lib/config/footer.tsx, lib/config/pages.tsx, styles/app.scss
=> feat: add a job for senior rust backend developer

components/layout/footer.tsx, lib/config/footer.tsx, lib/config/pages.tsx
=> feat: remove jobs

lib/config/footer.tsx, lib/config/pages.tsx
=> feat: add a job for production

styles/invitation.scss
=> fix: the font style

app/invitation/expired/page.tsx, components/invitation/expired-description.tsx, components/invitation/invite-owner.tsx, components/invitation/invite-workspace.tsx
=> chore: update copy for invitation expire page

components/invitation/expired-description.tsx
=> chore: remove bold style for user name

app/layout.tsx, lib/config/home.tsx, lib/config/navigation.tsx
=> fix: modified some data

components/about/scroll-logos.tsx
=> fix: scroll logos

lib/config/home.tsx
=> fix: modified copy of home page

components/about/scroll-logos.tsx
=> fix: the error width

lib/config/home.tsx
=> fix: modified copy

components/download/modal-download.tsx, components/pricing/unlock.tsx
=> fix: modified some copy

components/layout/footer.tsx
=> fix: copyright

components/shared/mobile-download-btns.tsx, lib/hooks/use-download.tsx
=> feat: replace ios download link

lib/hooks/use-download.tsx
=> fix: ios link

components/template-center/templates.tsx
=> fix: modified templates layout

components/pricing/price-config.ts
=> fix: modified free plan

app/layout.tsx, components/layout/app.tsx, package.json, public/robots.txt, public/sitemap.xml, scripts/generate-sitemap.js
=> fix: add sitemap for seo

app/compare/notion-vs-appflowy/page.tsx, lib/config/home.tsx, lib/config/pages.tsx
=> fix: open import entry

app/blog/[slug]/page.tsx, app/blog/page.tsx, components/blog/post-item.tsx, components/product/communities.tsx
=> fix: blog seo

app/blog/feed.xml/route.ts, app/blog/page.tsx
=> fix: blog page desc

components/template-center/template-item.tsx, components/template-center/template/template-section.tsx, lib/interface.ts
=> fix: template info

components/layout/app.tsx
=> fix: add google ads id

app/.well-known/apple-app-site-association/route.ts, app/.well-known/assetlinks.json/route.ts, components/blog/articles.tsx, components/blog/post-item.tsx
=> fix: add applink

components/product/main-download.tsx
=> fix: modified copy text

app/.well-known/apple-app-site-association/route.ts, app/.well-known/assetlinks.json/route.ts
=> fix: modified universal link path

components/layout/nav/navbar-popover.tsx, lib/collect.ts
=> fix: add collect event

components/pricing/price-config.ts
=> fix: modified free plan 20 AI response to 10

components/layout/footer.tsx, lib/config/footer.tsx
=> fix: modified 2024 to 2025 and add zapier entry

app/pricing/page.tsx, lib/config/footer.tsx, lib/config/navigation.tsx
=> chore: update link of help article
